///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MergeIssues
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MergeIssuesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ca74b7c9-435e-41a6-b806-4f3c60ac3202")]
    public partial class MergeIssuesRepository : RepoGenBaseFolder
    {
        static MergeIssuesRepository instance = new MergeIssuesRepository();

        /// <summary>
        /// Gets the singleton class instance representing the MergeIssuesRepository element repository.
        /// </summary>
        [RepositoryFolder("ca74b7c9-435e-41a6-b806-4f3c60ac3202")]
        public static MergeIssuesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MergeIssuesRepository() 
            : base("MergeIssuesRepository", "/", null, 0, false, "ca74b7c9-435e-41a6-b806-4f3c60ac3202", ".\\RepositoryImages\\MergeIssuesRepositoryca74b7c9.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ca74b7c9-435e-41a6-b806-4f3c60ac3202")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MergeIssuesRepositoryFolders
    {
    }
#pragma warning restore 0436
}
